# Site settings
title: RoboPoto
description: People Developer
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://robopoto.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Roby Poteau
user_description: I have my doctorate in Operations Research so my skillset concerns taking data and making it useful. This has lead me to explore software development in more depth and become familiar with many of its tools. My desire is to share what I know and what I'm learning.
user_title: Researcher | Developer
email: robypoteau@gmail.com
instagram_username: robesmagobes
github_username:  robypoteau

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
