# site settings
title: RoboPoto
# email: youremailaddress@gmail.com
description: Consultant | Data Scientist | Software Developer
baseurl: # the subpath of your site, e.g. /blog
url: https://www.robopoto.com # the base hostname & protocol for your site
# author: 
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

socials:
  GitHub: https://github.com/robypoteau
  GitLab:
  Instagram: https://www.instagram.com/robesmagobes
  LinkedIn: https://www.linkedin.com/in/robypoteau
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- makefile
